# Generated by Django 4.2.16 on 2024-10-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='endDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='startDate',
            field=models.DateField(),
        ),
    ]
