# Generated by Django 4.2.16 on 2024-10-23 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems1', '0003_useraccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='user_role',
            field=models.CharField(choices=[('event manager', 'Event Manager'), ('attendee', 'Attendee')], max_length=20),
        ),
    ]
