# Generated by Django 4.2.16 on 2024-10-24 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ems1', '0004_attendee_alter_useraccount_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='ems1.event'),
        ),
    ]
