# Generated by Django 4.2.16 on 2024-10-24 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ems1', '0006_alter_attendee_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='event',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='ems1.event'),
        ),
    ]
