# Generated by Django 4.2.16 on 2024-11-26 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ems1', '0009_analytics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendee',
            old_name='event',
            new_name='event_id',
        ),
    ]
