# Generated by Django 4.2.16 on 2024-11-26 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ems1', '0010_rename_event_attendee_event_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendee',
            old_name='event_id',
            new_name='event',
        ),
    ]
