# Generated by Django 4.2.16 on 2024-12-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems1', '0012_alter_event_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=55, null=True),
        ),
    ]
